name: 'Test Setup Android CLI'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Test Setup Android CLI
        uses: ./
        with:
          cmdline-tools-version: '11076708'
          accept-licenses: 'true'

      - name: Verify sdkmanager
        run: sdkmanager --version
